### ISSUE TITLE
Support for updating existing Policy VCSRepo and PoliciesPath

### ISSUE THREAD

**Issue by etopeter** [hashicorp/go-tfe#105]
I would like to request a feature to add support for updating existing policies VCSRepo or PoliciesPath. Today one can only control attributes during creation.

I see it as adding those attributes to [PolicySetUpdateOptions](https://github.com/hashicorp/go-tfe/blob/master/policy_set.go#L200)

**Comment by lafentres** [comment]
Closing as this was addressed by #106
