### ISSUE TITLE
Plan to add support for registry modules?

### ISSUE THREAD

**Issue by jason-riddle** [hashicorp/go-tfe#107]
As the title mentions, has this been discussed at all?

**Comment by iiro** [comment]
This would be great...

**Comment by lafentres** [comment]
Hi there!

Support for registry modules would be great. This has been discussed and is definitely on our roadmap. We don't have an exact timeline at the moment but we're definitely planning to work on it.

**Comment by lafentres** [comment]
Just released support for this in #128! v0.10.0 has support for registry modules :]
