### ISSUE TITLE
Any CLI client using this library?

### ISSUE THREAD

**Issue by rgreinho** [hashicorp/go-tfe#108]
I am wondering if there is already a CLI client that leverages this library? Something like [th-helper](https://github.com/hashicorp-community/tf-helper), but in Go?

If not is there any place to start such a project where we could contribute?

**Comment by chrisarcand** [comment]
Hi! I don't believe there's a Go version of th-helper (at least, from HashiCorp); the nearest thing to a CLI client in Go that uses this library would be The [Terraform Enterprise Provider](https://github.com/terraform-providers/terraform-provider-tfe/) used for Terraform itself. 

I'm no authority on policy regarding starting/moving third party projects in to any official HashiCorp organizations, so the best advice I have is to just start one on your own, if that's a thing you'd like to do. ❤️  Thanks!
