### ISSUE TITLE
Runs.Create occasionally fails with "invalid run parameters"

### ISSUE THREAD

**Issue by kvrhdn** [hashicorp/go-tfe#116]
Hi!

I've created an action that uses `go-tfe` to create new runs on Terraform Cloud as part of our delivery pipeline. This works pretty well, but the execution of `Runs.Create` fails _occasionally_ with a fairly cryptic error `Invalid Attribute: invalid run parameters`

Error in the context of GitHub Actions 👇

<img width="1130" alt="Screenshot 2020-04-23 at 00 28 23" src="https://user-images.githubusercontent.com/7748404/80040421-53bff180-84fa-11ea-9651-6d530b6563f9.png">

You can find the exact code I'm using here: https://github.com/kvrhdn/tfe-run/blob/master/main.go#L68

I haven't been able to pinpoint anything that could cause this:
- it happens both on speculative and non-speculative runs
- it happens both on runs that have changes and runs that don't have
- the error is always caused by `Runs.Create`, I haven't seen any other error messages
- re-triggering the job sometimes works, but I've also seen it fail multiple times after each other (over a span of 15+ minutes)

So I've been pretty puzzled 😕  Maybe you recognize the error and provide some pointers? Is there anything I can do to log more trace data?

Thanks!

**Comment by kvrhdn** [comment]
This is an example of a run that failed: https://github.com/kvrhdn/tfe-run/runs/615742070?check_suite_focus=true
While a later run succeeded: https://github.com/kvrhdn/tfe-run/runs/615783144?check_suite_focus=true

**Comment by kvrhdn** [comment]
Since I've updated go-tfe [from 0.6.0 to 0.7.0](https://github.com/kvrhdn/tfe-run/commit/7523ab7d1ef1bd8a86554c2158a9eb6237aa98f2), my errors have changed slightly. I now get:
```
Error: could not create run: unprocessable entity

invalid run parameters
```
Not sure if this is still the same issue, but I'd guess so since this occurs on the exact same spot.

An exampe of a recent run in which this occurred: [kvrhdn/tfe-run/runs/617158935](https://github.com/kvrhdn/tfe-run/runs/617158935?check_suite_focus=true)

**Comment by kvrhdn** [comment]
For anyone else encountering this issue, I've been able to work around this by wrapping the call to `Runs.create` with a basic retry function.
See: https://github.com/kvrhdn/tfe-run/blob/master/main.go#L102

Since then, my integration tests haven't failed anymore 🙂 (purple = success, orange = a failed test)
<img width="1431" alt="Screenshot 2020-04-27 at 10 00 02" src="https://user-images.githubusercontent.com/7748404/80384002-9db32980-88a4-11ea-8d9e-8f8d3218a4fa.png">

**Comment by rdlang** [comment]
@kvrhdn I encountered a similar issue, although I am not using `go-tfe`. In my case there seemed to be a race condition between creation of a workspace and applying a run.

It could also explain why the retry makes your code work.

**Comment by jgiannuzzi** [comment]
Hi @kvrhdn, I think this happens when you create your run whilst the configuration version is not yet in `uploaded` status.

Terraform CLI waits for the status to change before creating the run: https://github.com/hashicorp/terraform/blob/v0.13.1/backend/remote/backend_plan.go#L204-L231

**Comment by kvrhdn** [comment]
Oh, that's interesting @jgiannuzzi! I hadn't considered this code would also exist within Terraform. I'll try this out, thanks.

**Comment by kvrhdn** [comment]
The solution described by @jgiannuzzi fixed it for me!

So this error occurs when you create a run while the configuration version is still in status pending. The client should wait until the configuration version has status uploaded. This is described here [_Configuration Version Status_](https://www.terraform.io/docs/cloud/api/configuration-versions.html#configuration-version-status).

I missed this because this isn't described in [the documentation on the runs API](https://www.terraform.io/docs/cloud/api/run.html). So mentioning this might be an improvement.

I'm closing this since this isn't an issue in go-tfe.
