### ISSUE TITLE
Teams.List API does not support pagination

### ISSUE THREAD

**Issue by lanluo2020** [hashicorp/go-tfe#125]
Teams List API does not support pagination
// List all the teams of the given organization.
List(ctx context.Context, organization string, options TeamListOptions) (*TeamList, error)
```
    client.Teams.List(ctx, tfeOrgName, gotfe.TeamListOptions{
		ListOptions: gotfe.ListOptions{
			PageNumber: 10,
			PageSize:   10,
		},
```
It always return all the teams under the organization, however the same pagination works for the workspace List API

**Comment by SkYNewZ** [comment]
+1
This is because the request URL is wrong. Page size and page number are set in `include` param instead of having their own

```
INFO[0011] TFC successfully initiated                   
DEBU[0011] Processing page 1                            
TRAC[0011] URL being requested: https://app.terraform.io/api/v2/organizations/adeo/teams?include=&page%5Bnumber%5D=1&page%5Bsize%5D=1
```

https://www.terraform.io/docs/cloud/api/index.html#pagination

**Comment by sbunce** [comment]
lanluo2020 and I are coworkers.

It seems like this is working now. I was able to list 199 teams in 4 pages with a page size of 50.

**Comment by chrisarcand** [comment]
Yup! I'm happy to report we just added pagination to this endpoint (coincidentally already supported here in this client).

Thanks.
