### ISSUE TITLE
Support upload of code not on filesystem in ConfigurationVersions.Upload 

### ISSUE THREAD

**Issue by sgettys** [hashicorp/go-tfe#131]
I would like to be able to provide a slice of bytes directly to the upload of the configuration versions instead of requiring that the terraform code be on disk. This would allow for hosting terraform code to run workspaces in cloud storage buckets and reading into memory for transient upload.

Propose a new method on ConfigurationVersions interface of ConfigurationVerions.UploadBytes()

**Comment by annawinkler** [comment]
Thanks for submitting this issue! I'm wondering if the linked [PR](https://github.com/hashicorp/go-tfe/pull/150) addresses your concern?

**Comment by annawinkler** [comment]
Closing this issue out since it's been a number of months. Please let us know if there is still a concern.
