### ISSUE TITLE
Client should be able to read credentials from terraform.rc file

### ISSUE THREAD

**Issue by scottwinkler** [hashicorp/go-tfe#135]
The client should first check environment variables for credentials, then it should check the terraform.rc file. https://www.terraform.io/docs/commands/cli-config.html#credentials-1

**Comment by sebasslash** [comment]
Unfortunately this would be out scope for this client, as this kind of configuration is better reserved for upstream applications, i.e `terraform.rc` is a Terraform-specific configuration file. Closing & apologies.
