### ISSUE TITLE
VCSRepo struct missing webhook-url attribute for Registry Modules

### ISSUE THREAD

**Issue by scottwinkler** [hashicorp/go-tfe#138]
The VCS Repo struct should be like the following:

```
      "vcs-repo": {
        "branch": "",
        "ingress-submodules": true,
        "identifier": "lafentres/terraform-aws-my-module",
        "display-identifier": "lafentres/terraform-aws-my-module",
        "oauth-token-id": "ot-hmAyP66qk2AMVdbJ",
        "webhook-url": "https://app.terraform.io/webhooks/vcs/a12b3456..."
      },

```
documentation link: https://www.terraform.io/docs/cloud/api/modules.html#sample-response-3

Currently it is using the Workspace VCSRepo struct which lacks webhook-url 
```
type VCSRepo struct {
	Branch            string `json:"branch"`
	DisplayIdentifier string `json:"display-identifier"`
	Identifier        string `json:"identifier"`
	IngressSubmodules bool   `json:"ingress-submodules"`
	OAuthTokenID      string `json:"oauth-token-id"`
}
```

I propose either creating a new struct specifically for Registry Modules, or adding a new attribute to the workspace VCSRepo. Probably this code should be moved out of Workspace.go if that is the case

**Comment by sebasslash** [comment]
It only took 2 years... 😆 Closing! Thanks for reporting.
