### ISSUE TITLE
Should PolicySet struct include CurrentVersion and NewestVersion under relations?

### ISSUE THREAD

**Issue by rberlind** [hashicorp/go-tfe#149]
Based on https://www.terraform.io/docs/cloud/api/policy-sets.html#relationships, I think that https://github.com/hashicorp/go-tfe/blob/master/policy_set.go#L73 should include CurrentVersion and NewestVersion under Relations and that these would point at `jsonapi:"relation,current-version"` and `jsonapi:"relation,newest-version"` respectively.

I'm not sure if other changes would be needed.

**Comment by chrisarcand** [comment]
You would need a version struct to unmarshal with (which may come of your work in #150)

**Comment by rberlind** [comment]
I did not make or plan to make any changes in policy_set.go myself.

**Comment by uturunku1** [comment]
Closing this issue as it is being addressed on this PR https://github.com/hashicorp/go-tfe/pull/294
