### ISSUE TITLE
The Policy Set Versions API endpoints are not covered

### ISSUE THREAD

**Issue by rberlind** [hashicorp/go-tfe#151]
The [Policy Set Versions API endpoints](https://www.terraform.io/docs/cloud/api/policy-sets.html#create-a-policy-set-version) are not covered.

I am adding that in https://github.com/hashicorp/go-tfe/pull/150

**Comment by uturunku1** [comment]
This PR https://github.com/hashicorp/go-tfe/pull/230 closes this issue.
