### ISSUE TITLE
I am unable to get the upload link when creating a TF Module version

### ISSUE THREAD

**Issue by PatrickDale** [hashicorp/go-tfe#159]
Hello! I am hoping to use this library to create tooling to publish modules to a private registry, but do not see an upload link attribute in [RegistryModuleVersion](https://github.com/hashicorp/go-tfe/blob/master/registry_module.go#L87).

Are there plans to add this attribute? I see a related conversation in PR #150 (`Add policy set version`)

**Comment by chrisarcand** [comment]
Hi! As you already saw, there definitely is a need for properly handling [the JSON:API specification's document links](https://jsonapi.org/format/#document-links) in this client in general, which isn't immediately provided by the [google/jsonapi package](https://github.com/google/jsonapi). Once that's handled (which could happen independently of #150 of course), adding the upload link to this module version type would be great.

**Comment by shedimon** [comment]
@chrisarcand Is there any movement with this? Missing the URL to upload the module archive denies this package use for the modules related API

**Comment by omarismail** [comment]
Hey @shedimon, this is actively being worked on, and should be available in a new minor version release for go-tfe in about a week or so.

**Comment by shedimon** [comment]
Great news, thank you @omarismail!

**Comment by straubt1** [comment]
Here looking for exactly this.
Would also be great to get an Upload function similar to the Configuration Version Upload -> https://github.com/hashicorp/go-tfe/blob/9fb3b3a13d968df0e75b4e8ceadb539a9cdeaead/configuration_version.go#L36
