### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by valter-silva-au** [hashicorp/go-tfe#172]
Hi All,
I'm getting the following error when executing my CLI (in development) within a Docker container (`ubuntu:18.04`).

```
Get "https://app.terraform.io/api/v2/ping": x509: certificate signed by unknown authority 
```

Strangely enough, I don't get the same error when executing it from my MacBook. Any suggestions of how to solve this issue?

Thank you,
Valter.

**Comment by chrisarcand** [comment]
Hi!

Your Docker container likely does not have any CA certificates installed to check for the authenticity of SSL connections. 

You can likely fix this by doing something like `apt-get install ca-certificates` which will install [Ubuntu's common set of certificates](https://launchpad.net/ubuntu/+source/ca-certificates); but the solution may vary depending on your individual circumstances. 

Thanks!

**Comment by valter-silva-au** [comment]
That fixed the issue, thank you @chrisarcand!
