### ISSUE TITLE
[Question] Force Execute a Run

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/go-tfe#194]
Does `go-tfe` support the Force Execute option?
https://www.terraform.io/docs/cloud/api/run.html#forcefully-execute-a-run

I couldn't see an option in run.go
https://github.com/hashicorp/go-tfe/blob/master/run.go#L18

**Comment by chrisarcand** [comment]
It does not currently, no. A fair addition though!

**Comment by annawinkler** [comment]
Closing because this feature request was addressed via this PR #570 🥳
