### ISSUE TITLE
Support inclusion of related resources (include query param)

### ISSUE THREAD

**Issue by gwellington** [hashicorp/go-tfe#21]
Hey there!

Thanks for creating the Golang API for TFE!  I had a question about https://www.terraform.io/docs/enterprise/api/index.html#inclusion-of-related-resources and `go-tfe`'s support of related resources.

I was looking through the documentation (https://godoc.org/github.com/hashicorp/go-tfe) and I didn't see an option in the `ListOptions` struct to pass in additional query parameters.  I was specifically trying to identify how to return `created-by` in a workspace run which doesn't seem currently possible.  

Thanks!

**Comment by svanharmelen** [comment]
Thanks for your report @gwellington! And you are completely right that this isn't possible at this moment. This is mostly related to the underlying [package](https://github.com/google/jsonapi) that is used for the `JSON:API` marshaling.

There are a couple of features missing in that package which prevents us from implementing support for including resources. We currently work of a [fork](https://github.com/svanharmelen/jsonapi) and are looking into adding the missing pieces, but my guess is that this will take a while and that for the foreseeable future `go-tfe` will not support includes.

I've updated the title of this issue so it reflects the problem a bit better and others can (hopefully) find this issue if they have the same question. When there is any progress on this, I'll update the issue with any relevant info.

**Comment by gwellington** [comment]
@svanharmelen Thanks for the detailed info!  Sounds like the easiest workaround is to create a quick REST wrapper for what I need then.

**Comment by ngortheone** [comment]
Any updates? It is the end of 2020 and it is still impossible to get `created-by` of the run

**Comment by chrisarcand** [comment]
[Include parameters](https://jsonapi.org/format/#fetching-includes) have always been possible. Any `Read()` function just needs to have options passed with an `Include` field and the value will be properly encoded on GET requests as querystring; the jsonapi package can unmarshal the included relationships no problem.
