### ISSUE TITLE
Request for Agent Information...

### ISSUE THREAD

**Issue by muranant** [hashicorp/go-tfe#216]
Hi, 
Would like to request enhancement to list the Terraform Agent details within the agent Pool. The UI shows this detail but it is not available from the APIs.

thx
Murali

**Comment by chrisarcand** [comment]
Hi! This information is available as part of the [Agent Pools API](https://www.terraform.io/docs/cloud/api/agents.html#show-an-agent):

![image](https://user-images.githubusercontent.com/2430490/116938556-8d105e80-ac30-11eb-8007-748ecec75a15.png)

It is not available within this client, however, so leaving this open to track that!

**Comment by evilensky** [comment]
Apologies for commenting on a closed issue, but where can I find this interface in the client?  Thank you
