### ISSUE TITLE
Support Workspace Variables API (Variables API being deprecated?)

### ISSUE THREAD

**Issue by jcmcken** [hashicorp/go-tfe#228]
[This page](https://www.terraform.io/docs/cloud/api/variables.html) mentions the Variables API is being deprecated.

I don't yet see in the [SDK documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe#Variables) that the [workspace variables API](https://www.terraform.io/docs/cloud/api/workspace-variables.html) is yet supported

**Comment by chrisarcand** [comment]
The `Variables` interface in this client already uses the Workspace Variables API; that link in the package docs is incorrect and should be changed.
