### ISSUE TITLE
Managing Variable Sets API

### ISSUE THREAD

**Issue by rescDev** [hashicorp/go-tfe#284]
It seems like the client does not support the Variable Sets API yet.

https://www.terraform.io/docs/cloud/api/variable-sets.html

I would be up for contributing this, just wanted to create an issue for it. Maybe I just don't see it 😄

**Comment by chrisarcand** [comment]
Hello!

Indeed it does not; this feature is [currently in public beta](https://www.hashicorp.com/blog/terraform-cloud-variable-sets-beta-now-available) and the API is subject to change.

**Comment by rescDev** [comment]
Hi @chrisarcand , thanks for your answer. As it is in public beta and the API might change, does it make sense to implement this in go-tfe already then ?

**Comment by chrisarcand** [comment]
Generally speaking, beta APIs are not added to the client, correct. Note this is a general rule and exceptions are sometimes made.

For this particular API, addressing requests for client/provider support is on our (HashiCorp's) roadmap. Thanks for your patience!

**Comment by rbUUbr** [comment]
@chrisarcand great! 🎉 what's the ETA?

**Comment by nikolay** [comment]
I see variable sets are GA on TFC now. When will this get updated so that the TFE provider can get this long-awaited feature as well?
