### ISSUE TITLE
Missing endpoint for "update an organization's module consumers"?

### ISSUE THREAD

**Issue by Olgoetz** [hashicorp/go-tfe#287]
I have been looking for a while in the documentation for updating an organization's module consumers.

To more precise, I  look for this:
https://terraform.io/cloud-docs/api-docs/admin/organizations#update-an-organization-s-module-consumers

Does there already exist an endpoint for the go tfe client?

**Comment by brandonc** [comment]
@Olgoetz thanks for filing this issue. go-tfe is still catching up to covering the entire API, especially TFE admin endpoints, but I was able to add support for listing and updating module consumers for a future release https://github.com/hashicorp/go-tfe/pull/288

**Comment by brandonc** [comment]
Released in [v0.22.0](https://github.com/hashicorp/go-tfe/releases/tag/v0.22.0)
