### ISSUE TITLE
New TFE Run Status?

### ISSUE THREAD

**Issue by gwellington** [hashicorp/go-tfe#30]
Hey there!

We just updated to the latest version of TFE and noticed that there is a new status that is being returned by one of our workspaces via the API: 
```
"status": "planned_and_finished",
```
Looking at the current set of RunStatus, I don't see a corresponding one for the returned status.   Is that expected?  https://github.com/hashicorp/go-tfe/blob/faae81b2a4b7a955bd8566f4df8f317b7d1ddcd6/run.go#L50

Thanks,
Glenn

**Comment by svanharmelen** [comment]
Thanks for the report @gwellington! Added the missing run statuses in PR #31

**Comment by gwellington** [comment]
Thank you for the quick fix!
