### ISSUE TITLE
Support MS Teams as a destination for notifications

### ISSUE THREAD

**Issue by sethbacon** [hashicorp/go-tfe#418]
Terraform Cloud now supports MS teams. Can this be added to go-tfe to support downstream terraform-tfe-provider?
![image](https://user-images.githubusercontent.com/14307877/171502311-41419e40-cf13-4179-9f93-f16d9a811141.png)

**Comment by annawinkler** [comment]
Thank you for submitting this issue! We have a draft [PR](https://github.com/hashicorp/go-tfe/pull/389) open to add support for this functionality.

**Comment by sethbacon** [comment]
Thanks for the update, I missed that PR!

**Comment by annawinkler** [comment]
The PR has been [merged](https://github.com/hashicorp/go-tfe/commit/26d340140981799064f1f493b61b581b83777799), so closing this issue.
