### ISSUE TITLE
Support account creation

### ISSUE THREAD

**Issue by ctodea** [hashicorp/go-tfe#44]
Hi there,
I've read the [documentation](https://www.terraform.io/docs/enterprise/api/index.html) searching for a way to manage accounts via API. There are supported actions like updating account info or changing passwords, but couldn't find anything for account creation. Digging a bit in this repo I found [user.go] (https://github.com/hashicorp/go-tfe/blob/master/user.go) which looks like the place this could be defined, and seems there is no such thing.
I would expect something like:

> POST /account/new

with a JSON payload containing the username, mail and password (which is exactly what /account/new requires when used from a browser)

So, am I missing something, is this supported at all?
If not, is there any particular reason for it?

Thanks in advance.

**Comment by svanharmelen** [comment]
Hi @ctodea! You are correct that its currently not supported to manage user accounts via the API. The supported actions that you found are always related to the user who's token is used when making the API call. So in that sense you can only "manage" your own user account.

I don't think we have any plans to add support for creating and managing user accounts for other users. But maybe you can share your use case why this would be needed or helpful?

For organizations that want to have better control over their users we do offer SAML integration with authentication backends who support SAML. Maybe that can help in your use case?

**Comment by ctodea** [comment]
Thanks for your reply.
