### ISSUE TITLE
[Feature Request] Add "provider-binary-uploaded" to response

### ISSUE THREAD

**Issue by straubt1** [hashicorp/go-tfe#470]
When dealing with Provider Platforms within the Registry, there is an attribute that is helpful to determine if a platform version has been created, but has not been uploaded with the binary.

Request to have `RegistryProviderPlatforms.List()` and `RegistryProviderPlatforms.Read()` functions return the "provider-binary-uploaded" attribute of a registry provider platform.

Public Docs: https://www.terraform.io/cloud-docs/api-docs/private-registry/provider-versions-platforms#get-all-platforms-for-a-single-version

Go struct: https://github.com/hashicorp/go-tfe/blob/main/registry_provider_platform.go#L35

Potential code change
```
ProviderBinaryUploaded bool   `json:"provider-binary-uploaded"`
```

**Comment by annawinkler** [comment]
Thank you for submitting this issue! That seems like a reasonable request. ❤️

**Comment by annawinkler** [comment]
Addressed in merged PR.
