### ISSUE TITLE
Workspaces Create error: Pointer type in struct is not supported

### ISSUE THREAD

**Issue by corymhall** [hashicorp/go-tfe#48]
Hello, 

I am trying to create a new workspace and I am getting the following error:
```
Pointer type in struct is not supported
```

This is the code I am using. 

```
	config := &tfe.Config{
		Token: "ATLAS_TOKEN",
	}
	client, err := tfe.NewClient(config)
	if err != nil {
		log.Fatal(err)
	}
	ctx := context.Background()

	_, err = client.Workspaces.Create(ctx, "my-org", tfe.WorkspaceCreateOptions{
		Name:             tfe.String("workspace-name"),
		WorkingDirectory: tfe.String("directory"),
		VCSRepo: &tfe.VCSRepoOptions{
			Identifier:   tfe.String("org/repo-name"),
			OAuthTokenID: tfe.String("token"),
			Branch:       tfe.String("master"),
		},
	})

```

Any help you can provide would be greatly appreciated.

Thanks!

**Comment by svanharmelen** [comment]
Hi @corymhall! I just copied and pasted your code and I can compile this exact code without issues. Can you share some more details, like when exactly you get this error (e.g. during compilation of when running the compiled code)?

Also how did you manage you dependencies? Using Go modules or using a vendoring tool?

**Comment by corymhall** [comment]
@svanharmelen the code compiles fine, I get the error when running the code. I am using dep to manage vendoring and have the latest vendored from the master branch.

**Comment by svanharmelen** [comment]
Ah... I think this is a vendoring issue. Could you try to update your `Gopkg.toml` by adding:

```
[[override]]
branch = "master"
name = "github.com/svanharmelen/jsonapi"
```

And then run `dep ensure` to update your deps? `dep` will take the latest tagget release, but since we currently use a fork of the `jsonapi` package we didn't tag master.

But I guess this should get you going again...

**Comment by svanharmelen** [comment]
@corymhall did you manage to test this with the updated dependencies?

**Comment by lkysow** [comment]
I've confirmed this fixes the issue.

**Comment by edward-of-clt** [comment]
Wow. Small world. Thanks @corymhall for opening this. haha Still leaving the woodpile higher.
