### ISSUE TITLE
missing mocks for VariableSetVariables

### ISSUE THREAD

**Issue by wryfi** [hashicorp/go-tfe#492]
There are no mocks for `VariableSetVariables` and its related methods. It looks like mocks are autogenerated using `mockgen` so maybe `VariableSetVariables` is just missing from a build process somewhere? For now I have generated my own but it would be nice if I didn't have to.

**Comment by brandonc** [comment]
@wryfi Thanks for raising this issue! I think I can devise a way to protect against forgetting to add these mocks in the future, but for now I have added the missing ones.

**Comment by wryfi** [comment]
👍 thanks @brandonc appreciate the prompt response!
