### ISSUE TITLE
go-slug update breaks TF uploads with symlinks

### ISSUE THREAD

**Issue by jakeyheath** [hashicorp/go-tfe#507]
go-tfe utilizes [go-slug in their update functionality](https://github.com/hashicorp/go-tfe/blob/392b6391d911646ef772a84df95a7504f9538c78/configuration_version.go#L276). This [PR of go-slug](https://github.com/hashicorp/go-slug/pull/29) disallows symlinks be default and adds an option for the user to specify paths that symlinks should be allowed. However, go-tfe doesn't expose this new option to the user when calling [Update](https://github.com/hashicorp/go-tfe/blob/392b6391d911646ef772a84df95a7504f9538c78/registry_module.go#L46). 

We are currently utilizing go-tfe to package up a Terraform directory that contains symlinks, but getting the following error:

> failed to get relative path for file "<PATH_TO_SYMLINK>": Rel: can't make <PATH_TO_SYMLINK> relative to ../../modules

**Comment by Uk1288** [comment]
👋 @jakeyheath 

Thank you for submitting this issue! We'll take a look and get back to you about this.

**Comment by laurenolivia** [comment]
@jakeyheath Thanks for flagging! Would you mind providing any config (and steps) that may be helpful in recreating the issue? Feel free to X-out any sensitive info.

**Comment by laurenolivia** [comment]
Hi @jakeyheath, writing to inform you that I will be closing this ticket. If this error happens again, please open another ticket and provide any necessary config so our team is able to reproduce the issue. Thank you! ⭐
