### ISSUE TITLE
[Request] Notification Configurations trigger

### ISSUE THREAD

**Issue by kuroseets** [hashicorp/go-tfe#524]
I would like to see "assessment:drifted" and "assessment:failed" added to the Notification Configurations triggers.

**Comment by laurenolivia** [comment]
Thank you for submitting this issue! We'll take a look and get back to you.

**Comment by brandonc** [comment]
This was released in [v1.11.0](https://github.com/hashicorp/go-tfe/blob/main/CHANGELOG.md#v1110)
