### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by linc01n** [hashicorp/go-tfe#53]
When I run `go mod vendor` I have the following error

```
go: verifying github.com/hashicorp/go-slug@v0.2.0: checksum mismatch
	downloaded: h1:gekvezBc+9LwN3qC+lesrz0Qg36hhgge9z/an1FCHx4=
	go.sum:     h1:MVdZAkTmDsUi1AT+3NQDsn8n3ssnVSIHwiM6RcUHvE8=
```

**Comment by svanharmelen** [comment]
Hi @linc01n, I guess you are hitting this problem: https://github.com/golang/go/issues/29278

Please make sure you are using Go >= 1.11.4 and delete the module cache before trying again.
