### ISSUE TITLE
[Feature Request] Provide a rich set of mocks, stubs, and supporting infrastructure for testing functionality built on go-tfe

### ISSUE THREAD

**Issue by evilensky** [hashicorp/go-tfe#536]
👋 

(Apologies I am still learning about Go and testing)

Is it possible that this project provide tools/scaffolding/instructions on how to mock and test tools built with go-tfe?  

For example, terraform has a [very](https://github.com/hashicorp/terraform/blob/v1.2.0-alpha-20220328/internal/cloud/tfe_client_mock.go) [rich](https://github.com/hashicorp/terraform/blob/31fc22a0d243a53f306eb41adb57b867aa170041/internal/cloud/testing.go#L329) of scaffolding for testing interactions with Terraform Cloud and creating mock http responses.  Is it possible that this type of thing could be made a part of this project for others to re-use in a turnkey fashion, including instructions?

Thank you kindly!

**Comment by Uk1288** [comment]
Hi @evilensky 

The go-tfe mocks are available and located in the [mocks](https://github.com/hashicorp/go-tfe/tree/main/mocks) folder.

Here is an example of how the go-tfe mock is used in the [terraform-provider-tfe](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/run_task_helpers_test.go)

**Comment by evilensky** [comment]
Thank you this helps!
