### ISSUE TITLE
Audit Trails API pagination doesn't work

### ISSUE THREAD

**Issue by kono2021** [hashicorp/go-tfe#585]
# Description
Audit Trails API pagination structure is differ from other APIs therefore unmarshal doesn't work properly. `AuditTrailList.Pagination` is always `nil`.

https://github.com/hashicorp/go-tfe/blob/f2188c9d332444342dfba8771c3af9228fc86e21/audit_trail.go#L136-L141

Pagination struct tags don't match Audit Trails API Json response.

https://github.com/hashicorp/go-tfe/blob/f2188c9d332444342dfba8771c3af9228fc86e21/tfe.go#L774-L781

Audit Trails pagination structure is following

```
...
  "pagination": {
    "current_page": 1,
    "prev_page": null,
    "next_page": 2,
    "total_pages": 8,
    "total_count": 778
  }
}
```

**Comment by brandonc** [comment]
Thanks for reporting this. Our audit trails endpoint doesn't follow our standard API convention and unfortunately that wasn't noticed.
