### ISSUE TITLE
Go-slug v0.10.x breaks symlinks

### ISSUE THREAD

**Issue by alexlokshin-czi** [hashicorp/go-tfe#604]
Hi, 

We've previously opened https://github.com/hashicorp/go-tfe/issues/507, but it got closed with no resolution. With the release of go-slug v0.10.1 the issue re-surfaced again. If your tf folder structure contains symlinks and you're trying to publish to TFE, you'll experience the following error:

```
Rel: can't make /Users/username/full/path/terraform/modules relative to ../../modules
```

**Comment by sebasslash** [comment]
Hi @alexlokshin-czi  :wave: 

Thanks for reporting this issue!

Was wondering if you could shed some insight on how you are creating these symlinks? It seems there might something wonky with your symlink path but I have not yet been able to reproduce this error. That is, I've been able to successfully pack directories containing symlinks. 

Are these links resolving to a path existing outside your configuration directory? This is currently disabled when `go-slug` packs your target config path and we can potentially extend the `ConfigurationVersion` interface to allow for this.
