### ISSUE TITLE
go get no longer exist with latest go

### ISSUE THREAD

**Issue by araman-m** [hashicorp/go-tfe#624]
README tell to run go get command to install but this is no longer possible as this error out with 
go get -u github.com/hashicorp/go-tfe
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

looks like go get command was deprecated and has been completely removed with go 1.19

Please update README with the right command to install 
I tried unsuccesfully 
go install github.com/hashicorp/go-tfe@latest
package github.com/hashicorp/go-tfe is not a main package 

Using go 1.19.4 (latest version available via brew) on macosx 12.6

**Comment by brandonc** [comment]
@araman-m Thanks for reporting this! I think the word installation might have been overloaded in the README because there was no actual executable to install.
