### ISSUE TITLE
[Feature] AdminWorkspaceListOptions - Add Sort and Filter capabilities

### ISSUE THREAD

**Issue by cyberious** [hashicorp/go-tfe#640]
The current package needs the capabilities of Filter and Sort that are documented in the API. 

The current workaround is to grab all Workspaces with the IncludeOptions to include CurrentRuns and other objects I am attempting to filter. It would be advantageous to have this in `go-tfe` as well, as it would drastically cut down the processing time for our end users.

**Comment by laurenolivia** [comment]
Thank you for flagging @cyberious. Our team will look into this.
