### ISSUE TITLE
unauthorized only in container

### ISSUE THREAD

**Issue by hitmenow** [hashicorp/go-tfe#71]
Hi, I'm having an issue where, I have created a working go script that will create a workspace. When I attempt to run this script inside a golang container, with the same API token, I get unauthorized error. Is this anything you have come across before? My Dockerfile is below, and script

```
FROM golang:1.12.4

WORKDIR /go/src/app
ADD tfe-build.go tfe-build.go

RUN go get -d -v ./...
RUN go install -v ./...
```

```
package main

import (
	"context"
	"log"
	"os"
	"flag"

	tfe "github.com/hashicorp/go-tfe"
)

func main() {
	tfe_workspace_name := flag.String("tfe_workspace_name", "foo", "name of workspace to be created")
	tfe_version := flag.String("tfe_version", "0.11.1", "tfe version to use")
	tfe_working_dir := flag.String("tfe_working_dir", "", "working directory")

	flag.Parse()
	config := &tfe.Config{
		Token: "blahblah.atlasv1.blahblahblahblah",
	}
	client, err := tfe.NewClient(config)
	if err != nil {
		log.Print("cant make client")
		log.Print(config)
		log.Fatal(err)
	}
	log.Print(client)

	// Create a context
	ctx := context.Background()

	// Check is workspace exists
	r, err := client.Workspaces.Read(ctx, "dci", *tfe_workspace_name)
	if err == nil {
		log.Print(r.VCSRepo)
		log.Print("workspace already exists")
		os.Exit(0)
	}

	log.Print(err)
...```

Thanks

**Comment by svanharmelen** [comment]
Hi @hitmenow, that is certainly unexpected and to be honest I cannot explain why this would happen. Could you share the exact error message to see if that reveals any additional information?

And when exactly do you get the error? When creating the new client, or when you try to read the workspace? And can you make sure (log) the flags contain the expected values when using the container?

Thanks!

**Comment by hitmenow** [comment]
Is there a way to get more verbose output? If I go run -v, I don't get any more output. When I log.Print(client), I get what looks like the correct token, and some other info that I can't interpret. Is this what you mean by log flag containing the expected values?
```
2019/04/16 13:35:28 &{0xc0000f8000 blahblah.atlasv1.blahblahblah map[User-Agent:[go-tfe]] 0xc000092420 0xc0004d40a0 <nil> false 0xc000090018 0xc000090020 0xc000090028 0xc000090050 0xc000090058 0xc000090060 0xc000090068 0xc000090070 0xc000090078 0xc000090088 0xc000090090 0xc000090098 0xc0000900a0 0xc0000900a8 0xc0000900b0 0xc0000900b8 0xc0000900c0 0xc0000900c8 0xc0000900d0 0xc0000900d8 0xc0000900e0}
```
Then when I try to read a workspace, the error is simply,
```
2019/04/16 13:35:28 unauthorized
```

Thanks for the response.

**Comment by svanharmelen** [comment]
Are you targeting a PTFE installation by any change?

**Comment by hitmenow** [comment]
Yes it's ptfe

**Comment by svanharmelen** [comment]
Ah, that explains a lot. You are not setting an `address`, so it will default to `https://app.terraform.io`. That will of course not work as both your user and org do not exist there.

But then this code should also not work on your local machine, unless you exported `TFE_ADDRESS` with the correct PTFE address?

Either way it should be fixed after you set the correct `address`.

**Comment by hitmenow** [comment]
You are 100% correct! Thank you I forgot I set this value!

**Comment by svanharmelen** [comment]
Glad we got it sorted 👍
