### ISSUE TITLE
AdminSAMLSetting struct does not support signature-signing-method and signature-digest-method attributes

### ISSUE THREAD

**Issue by karvounis-form3** [hashicorp/go-tfe#730]
The `AdminSAMLSetting` struct does not support the `signature-signing-method` and `signature-digest-method` fields when hitting the `GET /api/v2/admin/saml-settings` endpoint.

The response for TFE v202305-2 contains the above fields in its JSON response:
```
{
  "data": {
    "id": "saml",
    "type": "saml-settings",
    "attributes": {
      "enabled": true,
      "debug": true,
...
      "signature-signing-method": "SHA256",
      "signature-digest-method": "SHA1",
...
    }
  }
}
```

**Comment by uturunku1** [comment]
We usually don't have them scheduled ahead of time. We do releases as needed:

- This would be needed when someone from another team has code in one of these projects they need released for their work.
- Or when we’ve had enough other PRs (from external sources or our teams) that a release makes sense.

How soon would you need a release? @karvounis-form3

**Comment by uturunku1** [comment]
Ok! I'll mention to this to my team so we can work on a release sooner rather than later.

**Comment by uturunku1** [comment]
@karvounis-form3 The new release is available: https://github.com/hashicorp/go-tfe/releases
