### ISSUE TITLE
missing function(s) to get workspace-resources 

### ISSUE THREAD

**Issue by stefan-kiss** [hashicorp/go-tfe#754]
Hello,

thank you for a very useful library.
I'm looking but I can't find the library equivalent of this API: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspace-resources

am I missing something? and if not could this be implemented ? 

later-edit: if the project is open to contributions could submit a pr...

**Comment by sebasslash** [comment]
Hey @stefan-kiss ! Thanks for submitting this request. We are indeed missing support for this endpoint. If you are interested in opening a PR, here is the acceptance criteria:

- A new interface `WorkspaceResources` is defined with a `List(ctx context.Context, workspaceID string)` method. The godocs should link to the Workspace Resources API docs.
- A `WorkspaceResource` type is defined, encapsulating all the fields for a workspace resource.
- Pagination works as intended. 

Writing tests for this will not be straightforward. You will need to create a run that provisions some resources in the workspace. To do so, make use of `createRunApplied()` helper which uses `test-fixtures/config-version` as the config. Modify that config with a `count = 10` or something similar so you have multiple workspace resources. Lastly, workspace resources are processed asynchronously, so you will need to poll the workspace again for `workspace.ResourcesProcessed = true` before attempting to validate that the resources.

**Comment by stefan-kiss** [comment]
Hello back. sorry for the delay got sidetracked. ( and i thought all the testing setup would be harder than it was )

here is the PR https://github.com/hashicorp/go-tfe/pull/820

i saw that there is a statefile that is uploaded in Workspace tests, so i just used that. It's kind of simple. i could generate a more complicated one to have more teste cases, or several if needed.
