### ISSUE TITLE
Project name attr is not returned properly

### ISSUE THREAD

**Issue by nicolaka** [hashicorp/go-tfe#764]
Hello! Looks like Project.Name attr isn't returned. Only Project.ID is being returned when referencing Project.Name https://pkg.go.dev/github.com/hashicorp/go-tfe#Project.

**Comment by brandonc** [comment]
@nicolaka Hi! Thanks for filing an issue. Can you clarify when the Name attr isn't returned? If it is part of a relationship, this is the expected behavior unless you specify projects in the Include option. For example, when reading a workspace, adding the [WSProject include option to WorkspaceReadOptions](https://github.com/hashicorp/go-tfe/blob/v1.33.0/workspace.go#L242)

**Comment by nicolaka** [comment]
@brandonc I currently have the below include options but still getting `terraform-cloud-exporter-exporter-1    | level=error ts=2023-09-07T19:15:49.982Z caller=collector.go:105 msg="Error from scraper" scraper=workspaces err="invalid value for \"include\" field, (organization=XXX, page=1)"`. current_run and organization are working just fine, but project is not.  What am I missing here ? [disclaimer, i'm a Go n00b ]

```
		Include: []tfe.WSIncludeOpt{
			"current_run",
			"organization",
			"project",
		}
```

**Comment by brandonc** [comment]
This looks like it should work, unless it wasn't supported by your version of Terraform Enterprise.

To bisect the issue a bit, try using curl to request the workspace with included project:

`curl -H "Authorization: Bearer TOKEN" https://app.terraform.io/api/v2/workspaces/ws-YOURWORKSPACEID?include=project`

The result should reveal a project in the "included" key:

```
...
"included": [
    {
      "id": "prj-kCf4xGySfmycScAS",
      "type": "projects",
      "attributes": {
        "name": "Default Project",
        "permissions": {
          "can-read": true,
          "can-update": true,
          "can-destroy": true,
          "can-create-workspace": true,
          "can-move-workspace": true,
          "can-deploy-no-code-modules": true,
          "can-read-teams": true,
          "can-manage-teams": true
        }
      },
      "relationships": {
        "organization": {
          "data": {
            "id": "hashicorp",
            "type": "organizations"
          },
          "links": {
            "related": "/api/v2/organizations/hashicorp"
          }
        }
      },
      "links": {
        "self": "/api/v2/projects/prj-kCf4xGySfmycScAS"
      }
    }
  ]
```

**Comment by nicolaka** [comment]
I'm using `go-tfe` version 1.33 with TFC. I'm getting a similar response when using curl, but not sure why it's not working. i'll test it in a bit and let you know. But for clarification, if I want to retrieve the project name, and i'm iterating over a workspace list using this:

```
workspacesList, err := config.Client.Workspaces.List(ctx, organization, &tfe.WorkspaceListOptions{
		ListOptions: tfe.ListOptions{
			PageSize:   pageSize,
			PageNumber: page,
		},
		Include: []tfe.WSIncludeOpt{
			"project",
			"current_run",
			"organization",
		},
	})
```

would I just reference it using `w.Project.Name` ? `w.Project.ID` is working as expected but given that the project name is provided under the attributes section, I wasn't sure how to reference it ?

**Comment by brandonc** [comment]
I just verified that this is a bug in `Workspaces.List`. We haver Over-zealous parameter validation!
