### ISSUE TITLE
Ingress Attribute endpoint missing

### ISSUE THREAD

**Issue by jamestoyer** [hashicorp/go-tfe#79]
It looks like there is an endpoint that is missing from the client, namely the `ingress-attribute`s endpoint. 

I can't seem to find direct documentation to it, although it is mentioned on the [configuration versions](https://www.terraform.io/docs/enterprise/api/configuration-versions.html#available-related-resources) API page in passing. However, it would be super useful to have this as it would allow us to work out when a run is associated to a PR or not

**Comment by BrendanThompson** [comment]
Came here looking for the exact same thing, have spent some time digging around the requests to find this too!
