### ISSUE TITLE
Policies.Create seems to ignore EnforcementMode

### ISSUE THREAD

**Issue by ElliotG** [hashicorp/go-tfe#8]
opts := tfe.PolicyCreateOptions{
			Name: tfe.String("Required-Tags-Policy"),
			Enforce: []*tfe.EnforcementOptions{
				{
					Path: tfe.String("Required-Tags-Policy" + ".sentinel"),
					Mode: tfe.EnforcementMode(tfe.EnforcementSoft),
				},
			},
		}
		client.Policies.Create(ctx, "my_sweet_sweet_org", opts)
	}

For me, it arrived in PTFE as "EnforcementHard"

**Comment by ElliotG** [comment]
This may be an issue with PTFE itself, I'm going to file a support ticket to check.

**Comment by svanharmelen** [comment]
Thanks for the report @ElliotG! This indeed seems to be a result of how the API currently works. Looking at the open issue(s) it looks like work is already being done to improve/fix this.

Will use this issue to track if we need to update anything in this package as well (once the API changes are done).
