### ISSUE TITLE
Support recent TFC/TFE API changes

### ISSUE THREAD

**Issue by alex-ikse** [hashicorp/go-tfe#838]
#### Use-cases

Each version of TFE/TFC add new API endpoints and/or new attributes, but `go-tfe` is not aligned automatically. 

When we want to add these features to `terraform-provider-tfe` we are limited by go-tfe support.

#### Attempted Solutions

No solution witout a `go-tfe` upgrade

#### Proposal

I've filled 2 PRs (#837 and #836) to add features I need to `go-tfe` (to be able to propose a PR for `terraform-provider-tfe`)

**Comment by brandonc** [comment]
We've evaluated a few methodologies in the past to code-generate this SDK, but there are a few technical hurdles. Internally, we try and keep go-tfe and the provider aligned with new features as they are released. I have addressed the individual PRs directly and appreciate you reporting and contributing the missing API attributes! And for this reminder to look into them!
