### ISSUE TITLE
Add the possibility to pass a custom ca certificate for private TFE installation

### ISSUE THREAD

**Issue by Olgoetz** [hashicorp/go-tfe#948]
#### Use-cases

We use AWS Lambda to interact with our privately hosted TFE distribution. When leveraging the go TFE API wrapper we constantly receive x509 certificate signed by unknown authority. I did not find an option to pass a custom certificate to the client.

#### Attempted Solutions

Tried to put in the lambda certificate folder but we cannot update the certificate storage.
I also tied to pass the pass of the certificate as env variable CA_CERT and CA_PEM.

#### Proposal

When initializing the client it would be great to have an option to pass a custom CA certificate or having a Boolean parameter to disable SSL dich as VerifySSL true/false

**Comment by brandonc** [comment]
@Olgoetz Hello, and thanks for raising the question. Do you use the same lambda when using the terraform CLI? Were you able to apply any sort of terraform configuration to make that work?

go-tfe (and terraform) transmit such sensitive information, we've been apprehensive to allow any configuration that bypasses SSL verification. It may be better to implement some SSL gateway that can invoke your lambda function?

**Comment by brandonc** [comment]
@Olgoetz I'm going to close this issue for now, hoping you found a way to offer a verifyable SSL endpoint to TFE.
